# Generated by Django 4.0.4 on 2022-05-09 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
