# Generated by Django 4.0.4 on 2022-05-10 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_actor_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='actormovie',
            table='actors_movies',
        ),
    ]
